# Generated by Django 3.2 on 2022-04-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=5, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('activitylevel', models.CharField(blank=True, choices=[(2, 'Exercise 1-3 times/week'), (4, 'Daily exercise or intense exercise 3-4 times/week'), (1, 'Sedentary: little or no exercise'), (3, 'Exercise 4-5 times/week')], max_length=200, null=True)),
            ],
        ),
    ]
