# Generated by Django 4.0.3 on 2022-04-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_form',
            name='activitylevel',
            field=models.CharField(blank=True, choices=[('1', 'Sedentary: little or no exercise'), ('4', 'Daily exercise or intense exercise 3-4 times/week'), ('3', 'Exercise 4-5 times/week'), ('2', 'Exercise 1-3 times/week')], max_length=200, null=True),
        ),
    ]
